#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : R-PKI
Version  : 0.1.14
Release  : 58
URL      : https://cran.r-project.org/src/contrib/PKI_0.1-14.tar.gz
Source0  : https://cran.r-project.org/src/contrib/PKI_0.1-14.tar.gz
Summary  : Public Key Infrastucture for R Based on the X.509 Standard
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-PKI-lib = %{version}-%{release}
Requires: R-PKI-license = %{version}-%{release}
Requires: R-base64enc
BuildRequires : R-base64enc
BuildRequires : R-gmp
BuildRequires : buildreq-R
BuildRequires : openssl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-PKI package.
Group: Libraries
Requires: R-PKI-license = %{version}-%{release}

%description lib
lib components for the R-PKI package.


%package license
Summary: license components for the R-PKI package.
Group: Default

%description license
license components for the R-PKI package.


%prep
%setup -q -n PKI
pushd ..
cp -a PKI buildavx2
popd
pushd ..
cp -a PKI buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718606416

%install
export SOURCE_DATE_EPOCH=1718606416
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-PKI
cp %{_builddir}/PKI/LICENSE %{buildroot}/usr/share/package-licenses/R-PKI/a2d67e472e71e17d62559e01ec807373337b7583 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/PKI/DESCRIPTION
/usr/lib64/R/library/PKI/INDEX
/usr/lib64/R/library/PKI/LICENSE
/usr/lib64/R/library/PKI/Meta/Rd.rds
/usr/lib64/R/library/PKI/Meta/features.rds
/usr/lib64/R/library/PKI/Meta/hsearch.rds
/usr/lib64/R/library/PKI/Meta/links.rds
/usr/lib64/R/library/PKI/Meta/nsInfo.rds
/usr/lib64/R/library/PKI/Meta/package.rds
/usr/lib64/R/library/PKI/NAMESPACE
/usr/lib64/R/library/PKI/NEWS
/usr/lib64/R/library/PKI/R/PKI
/usr/lib64/R/library/PKI/R/PKI.rdb
/usr/lib64/R/library/PKI/R/PKI.rdx
/usr/lib64/R/library/PKI/certs/RForge-ca.crt
/usr/lib64/R/library/PKI/certs/demo.crt
/usr/lib64/R/library/PKI/help/AnIndex
/usr/lib64/R/library/PKI/help/PKI.rdb
/usr/lib64/R/library/PKI/help/PKI.rdx
/usr/lib64/R/library/PKI/help/aliases.rds
/usr/lib64/R/library/PKI/help/paths.rds
/usr/lib64/R/library/PKI/html/00Index.html
/usr/lib64/R/library/PKI/html/R.css
/usr/lib64/R/library/PKI/tests/test.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/PKI/libs/PKI.so
/V4/usr/lib64/R/library/PKI/libs/PKI.so
/usr/lib64/R/library/PKI/libs/PKI.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-PKI/a2d67e472e71e17d62559e01ec807373337b7583
